### ISSUE TITLE
Default nuxt config missing `analyzeDir` value

### ISSUE THREAD

**Issue by Migushthe2nd** [nuxt/bridge#1032]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.19.0
- Nuxt Version:     2.17.2-28284499.5674f49
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Should be self-explanatory

### Describe the bug

Running `nuxi analyze` results in
```sh
ERROR  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

  at Object.rm (node:internal/fs/promises:722:38)
  at clearDir (node_modules/nuxi/dist/shared/nuxi.976cd438.mjs:11:20)
  at Object.run (node_modules/nuxi/dist/chunks/analyze.mjs:93:11)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7) 
```
The path here is the `analyzeDir` property in the nuxt config. This property does not seem to be assigned a default value (`"/<rootDir>/.nuxt/analyze"` as described in the [nuxt docs](https://nuxt.com/docs/api/nuxt-config#analyzedir)), nor be resolved for example in the nitro config creation. `buildDir` is resolved in this case:

https://github.com/nuxt/bridge/blob/1fa3dce0df0c3122275a7d914ba7404b5fd01241/packages/bridge/src/nitro.ts#L67-L69

### Additional context

Nitro enabled, Vite disabled.

When manually providing a value, `nuxi analyze` runs generates an html report.
```js
    analyzeDir: "./.nuxt/analyze",
```
However, this default path seems to be conflicting with the 'Starting stats server' step.

**Comment by dan1kov** [comment]
@danielroe @wattanx 
Is it assumed that the bundle analyzer works for Vite builds?

If I enable Nitro and Vite in the nuxt config, I need to add the 'analyzeDir' variable, otherwise the build won't start.
<img width="865" alt="image" src="https://github.com/nuxt/bridge/assets/6531160/a24b3066-db7d-463e-9835-e119dd4693ef">

Also, if the config includes 'target: 'static'', the build will fail and will be compiled through webpack.
https://github.com/nuxt/bridge/blob/b8bd3463bd9caa12c26b8ff2d53c28edd37241ed/packages/bridge/src/nitro.ts#L23
<img width="761" alt="image" src="https://github.com/nuxt/bridge/assets/6531160/98c52ee1-d3e7-42f4-9da8-f1e626160dec">

There is no content when the server with statistics starts up
<img width="551" alt="image" src="https://github.com/nuxt/bridge/assets/6531160/07ca1879-bfca-472f-9453-3c0593ffb4d0">
<img width="506" alt="image" src="https://github.com/nuxt/bridge/assets/6531160/e96cd3d2-bc6b-4faf-8f10-76c24a49e706">
<img width="348" alt="image" src="https://github.com/nuxt/bridge/assets/6531160/2add616f-2d09-45cf-aa44-64b7fad89729">
<img width="377" alt="image" src="https://github.com/nuxt/bridge/assets/6531160/27a30391-3248-4d7b-b083-62d54649c8d1">
