### ISSUE TITLE
Support for vue runtime compiler

### ISSUE THREAD

**Issue by LionelPaulus** [nuxt/bridge#1054]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.0`
- Nuxt Version:     `2.17.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@9.8.1`
- Builder:          `webpack`
- User Config:      `bridge`, `alias`, `modern`, `ssr`, `components`, `head`, `css`, `loading`, `plugins`, `render`, `router`, `modules`, `buildModules`, `image`, `runtimeConfig`, `env`, `styleResources`, `vue`, `build`, `hooks`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `nitro`
- Runtime Modules:  `nuxt-runtime-compiler@1.3.0`, `@nuxtjs/style-resources@0.1.2`, `@nuxtjs/i18n@7.3.1`, `cookie-universal-nuxt@2.2.2`
- Build Modules:    `()`, `@nuxt/image@0.7.1`, `~/modules/generate-redirects`, `@storyblok/nuxt-2/module@3.0.0`, `@nuxt/bridge@3.0.0-rc.4-28407367.8f1f89e`

### Reproduction

Same as in this issue: https://github.com/nuxt/nuxt/issues/13843#issue-1549581747

### Describe the bug

This has been fixed [for Nuxt 3 in this PR](https://github.com/nuxt/framework/pull/4762) but how to solve the issue with Nuxt-bridge?

I tried using [nuxt-runtime-compiler](https://www.npmjs.com/package/nuxt-runtime-compiler) but it didn't work.

Thanks!

**Comment by LionelPaulus** [comment]
@huang-julien as you are both the author and the solver of the original issue, maybe you can help? 🙏

**Comment by huang-julien** [comment]
Hi :wave: 

I don't have the issue on your stackblitz 🤔

**Comment by jcwieme** [comment]
Hi @huang-julien 👋 
The error appears when we build for ssr and preview (`npm run build && node .output/server/index.mjs`)
If the string we're passing through contains only Vue components, it works.
```
<div>
  <component is="nuxt-logo" />
  <NuxtLogo />
</div>
```
But if you mix classic html tags with text, you'll get an error.
```
<div>
  <component is="nuxt-logo" />
  <NuxtLogo2 />
  if we add <bold>text</bold>
</div>
```

> [nuxt] [request error] [unhandled] [500] Cannot convert object to primitive value
>   at RegExp.test (<anonymous>)
>   at ./.output/server/chunks/handlers/renderer.mjs:557:43340
>   at Object.chars (./.output/server/chunks/handlers/renderer.mjs:557:43667)
>   at Kr.warn (./.output/server/chunks/handlers/renderer.mjs:557:40751)
>   at Kr (./.output/server/chunks/handlers/renderer.mjs:557:41891)
>   at to (./.output/server/chunks/handlers/renderer.mjs:557:64137)
>   at t (./.output/server/chunks/handlers/renderer.mjs:557:64679)
>   at ./.output/server/chunks/handlers/renderer.mjs:557:63648
>   at lo (./.output/server/chunks/handlers/renderer.mjs:557:66092)
>   at go (./.output/server/chunks/handlers/renderer.mjs:557:69819)
