### ISSUE TITLE
[unhandledRejection] Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by chz** [nuxt/bridge#24]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27266415.3ab12f9f`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27266907.929a634`
```

### Describe the bug

```
 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client                                                                                                                     14:23:45

  at new NodeError (internal/errors.js:322:7)
  at ServerResponse.setHeader (_http_outgoing.js:561:11)
  at send (node_modules/webpack-dev-middleware/dist/utils/compatibleAPI.js:68:7)
  at processRequest (node_modules/webpack-dev-middleware/dist/middleware.js:186:31)
  at ready (node_modules/webpack-dev-middleware/dist/utils/ready.js:11:12)
  at Object.middleware (node_modules/webpack-dev-middleware/dist/middleware.js:44:24)
  at node_modules/pify/index.js:33:11
  at new Promise (<anonymous>)
  at Object.<anonymous> (node_modules/pify/index.js:6:9)
  at Object.apply (node_modules/pify/index.js:80:20)
  at WebpackBundler.middleware (node_modules/@nuxt/webpack-edge/dist/webpack.js:1909:37)
  at middleware (node_modules/@nuxt/nitro/dist/index.mjs:1809:50)
  at node_modules/h3/dist/index.mjs:111:24
  at new Promise (<anonymous>)
  at callHandle (node_modules/h3/dist/index.mjs:108:10)
  at Object.handle (node_modules/h3/dist/index.mjs:104:12)
```

### Reproduction

Fresh install nuxt 2 and migrate to bridge following: https://v3.nuxtjs.org/getting-started/bridge

**Comment by danielroe** [comment]
I'm closing this as this should be resolved with https://github.com/nuxt/bridge/pull/324. If you encounter this again, feel free to open a new issue with a reproduction.

**Comment by m0rtyn** [comment]
I encountered with this issue. Migrated existing Nuxt2 project with Nuxt Bridge

```bash
 ERROR  [uncaughtException] Cannot set headers after they are sent to the client

  at ClientRequest.setHeader (_http_outgoing.js:558:11)
  at ProxyServer.<anonymous> (node_modules/nitropack/dist/chunks/prerender.mjs:2444:16)
  at ProxyServer.emit (node_modules/eventemitter3/index.js:184:35)
  at ClientRequest.<anonymous> (node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:133:16)
  at ClientRequest.emit (events.js:327:22)
  at ClientRequest.EventEmitter.emit (domain.js:467:12)
  at tickOnSocket (_http_client.js:778:7)
  at onSocketNT (_http_client.js:817:5)
  at processTicksAndRejections (internal/process/task_queues.js:81:21)
  ```
