### ISSUE TITLE
nuxi generate fetches api

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/bridge#28]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v17.0.1`
- Nuxt Version:     `2.16.0-27273615.ab1c6cb4`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `target`, `bridge`, `vite`, `alias`, `nitro`, `ssr`, `head`, `css`, `plugins`, `components`, `tailwindcss`, `buildModules`, `modules`, `serverMiddleware`, `watch`, `privateRuntimeConfig`, `build`, `storybook`   
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@4.2.1`, `portal-vue/nuxt`, `@nuxt/postcss8@1.1.3`, `@pinia/nuxt@0.1.0`, `nuxt-route-meta@2.3.2`, `@nuxt/bridge@3.0.0-27283410.c53b6a5`

### Reproduction

https://github.com/JabRef/JabRefOnline/pull/480, and in particular the "build" step in https://github.com/JabRef/JabRefOnline/runs/4218058544?check_suite_focus=true 

### Describe the bug

`nuxi generate` tries to access the api hosted at `localhost` during server build. On github workflow, this fails with the following error

``̀ 
Network error  FetchError: request to http://localhost:3000/api failed, reason: connect ECONNREFUSED 127.0.0.1:3000

    at file:///home/runner/work/JabRefOnline/JabRefOnline/node_modules/.cache/nuxt/nitro/index.mjs:62754:14
    at Object.error (file:///home/runner/work/JabRefOnline/JabRefOnline/node_modules/.cache/nuxt/nitro/index.mjs:62557:29)
    at notifySubscription (file:///home/runner/work/JabRefOnline/JabRefOnline/node_modules/.cache/nuxt/nitro/index.mjs:56593:13)
    at onNotify (file:///home/runner/work/JabRefOnline/JabRefOnline/node_modules/.cache/nuxt/nitro/index.mjs:56632:3)
    at SubscriptionObserver2.error (file:///home/runner/work/JabRefOnline/JabRefOnline/node_modules/.cache/nuxt/nitro/index.mjs:56673:5)
    at file:///home/runner/work/JabRefOnline/JabRefOnline/node_modules/.cache/nuxt/nitro/index.mjs:57747:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

``̀

**Comment by danielroe** [comment]
This should now be resolved with https://github.com/nuxt/bridge/pull/324. Let me know if not and we can reopen.
