### ISSUE TITLE
bug with local defu@5.0

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/bridge#306]
### Environment

Nuxt project info:                                                                                                                                                                                 11:18:15

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.18`
- Builder:          `webpack`
- User Config:      `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27498038.f18e68b`
------------------------------

### Reproduction

https://codesandbox.io/s/8c67w8?file=/package.json

### Describe the bug

when local already install defu@5.0, and set config 
```js
bridge:{
    meta:true
}
```
`yarn dev` will show :
```
[nuxt] [request error] Object(...) is not a function
  at Vue.<anonymous> (./.nuxt/dist/server/server.js:3928:63)  
  at Vue.computedGetter [as $$state] (./node_modules/vue/dist/vue.runtime.common.dev.js:4846:15)  
  at RefImpl.computedGetter [as value] (./.nuxt/dist/server/server.js:6293:29)  
  at ./.nuxt/dist/server/server.js:7459:41  
  at Array.forEach (<anonymous>)  
  at Object.get headTags [as headTags] (./.nuxt/dist/server/server.js:7458:19)  
  at renderHeadToString (./.nuxt/dist/server/server.js:7578:26)  
  at Object.nuxtApp.ssrContext.renderMeta (./.nuxt/dist/server/server.js:3955:114)  
  at renderHTML (./.nuxt/dev/index.mjs:438:38)  
  at ./.nuxt/dev/index.mjs:429:18
```
i  change `defu@6.0` fix this issue, if u think this is not `bug`, free to close this issue

**Comment by pi0** [comment]
Hi @baixiaoyu2997 yes you should install defu v6 (or later version).
