### ISSUE TITLE
 ERROR  Cannot start nuxt:  Cannot find any-observable implementation

### ISSUE THREAD

**Issue by HendrikJan** [nuxt/bridge#326]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.15.8`
- Package Manager:  `npm@8.5.5`
- Builder:          `webpack`
- User Config:      `rootDir`, `env`, `bridge`, `telemetry`, `nitro`, `head`, `publicRuntimeConfig`, `css`, `plugins`, `components`, `buildModules`, `vuetify`, `i18n`, `modules`, `compilerOptions`, `build`, `watchers`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@nuxtjs/vuetify@1.12.3`, `@nuxtjs/i18n@7.2.2`, `@nuxtjs/dotenv@1.4.1`, `@nuxt/bridge@3.0.0-27498038.f18e68b`
------------------------------

### Reproduction

Unfortunately I do not know how to reproduce.
The error does not occur locally but does occurs on the server (both nodejs v16.15.0).

### Describe the bug

When running `npx nuxi dev` (I cannot use `nuxi build` because of #27 ) I get the error:

```
 ERROR  Cannot start nuxt:  Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").

  at loadImplementation (node_modules/any-observable/register.js:29:9)
  at node_modules/any-observable/loader.js:30:18
  at Object.<anonymous> (node_modules/any-observable/index.js:2:39)
  at Module._compile (node:internal/modules/cjs/loader:1105:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at Module.require (node:internal/modules/cjs/loader:1005:19)
  at require (node:internal/modules/cjs/helpers:102:18)
  at Object.<anonymous> (node_modules/@samverschueren/stream-to-observable/index.js:2:20)
  at Module._compile (node:internal/modules/cjs/loader:1105:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at Module.require (node:internal/modules/cjs/loader:1005:19)
  at require (node:internal/modules/cjs/helpers:102:18)

```

So both "dev" and "build" fail and I cannot use anything on the server.

### Additional context

```
npm why any-observable

any-observable@0.3.0 dev
node_modules/any-observable
  any-observable@"^0.3.0" from @samverschueren/stream-to-observable@0.3.1
  node_modules/@samverschueren/stream-to-observable
    @samverschueren/stream-to-observable@"^0.3.0" from listr@0.14.3
    node_modules/listr
      peer listr@"^0.14.2" from listr-update-renderer@0.5.0
      node_modules/listr-update-renderer
        listr-update-renderer@"^0.5.0" from listr@0.14.3
      listr@"^0.14.3" from nitropack@0.2.11
      node_modules/nitropack
        nitropack@"^0.2.7" from @nuxt/bridge@3.0.0-27498038.f18e68b
        node_modules/@nuxt/bridge
          dev @nuxt/bridge@"npm:@nuxt/bridge-edge@^3.0.0-27498038.f18e68b" from the root project
```

**Comment by HendrikJan** [comment]
Solved :-)
It seems that this had to so with Cypress and not Nuxt.

The error started after issuing "npm remove cypress".
I had to TOTALLY remove cypress (also from package-lock.json and deleting node_modules) to solve this.
