### ISSUE TITLE
Export named 'defu' not found with nuxt bridge and vite

### ISSUE THREAD

**Issue by JamieCurnow** [nuxt/bridge#329]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.4.1`
- Builder:          `vite`
- User Config:      `bridge`, `target`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27498038.f18e68b`
------------------------------

### Reproduction

Create a new nuxt 2 app:

`npm init nuxt-app defu-bug`

I chose the following options, but I guess `language: TypeScript` is potentially the only important one?:
```
? Project name: defu-bug
? Programming language: TypeScript
? Package manager: Npm
? UI framework: None
? Nuxt.js modules: None
? Linting tools: None
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Static (Static/Jamstack hosting)
? Development tools: None
? What is your GitHub username? jamiecurnow
? Version control system: Git
```

---------------

Follow the migration guide to update to bridge:
https://v3.nuxtjs.org/bridge/overview

For example...

Make sure your dev server (nuxt dev) isn't running, remove any package lock files (package-lock.json and yarn.lock), and install the latest nuxt-edge:

```
package.json
- "nuxt": "^2.15.0"
+ "nuxt-edge": "latest"
```

Then, reinstall your dependencies:

`npm install`

Install @nuxt/bridge-edge as a development dependency:

`npm install -D @nuxt/bridge@npm:@nuxt/bridge-edge`

Update scripts in `package.json`:

```
{
  "scripts": {
-   "dev": "nuxt",
+   "dev": "nuxi dev",
-   "build": "nuxt build",
+   "build": "nuxi build",
-   "start": "nuxt start",
+   "start": "nuxi preview"
  }
}
```

Rename `nuxt.config.js` to `nuxt.config.ts` and update the default export:

```
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  // Your existing configuration
})
```

Update `tsconfig.json`

```
{
+ "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    ...
  }
}
```

---------------

Then update the `nuxt.config.ts` to remove `"@nuxt/typescript-build"` from `buildModules`.

Then enable vite:

```
export default defineNuxtConfig({
  bridge: {
    vite: true,
  },
  ...
}
```

Then `npm run dev`.

The app will build, but open the browser and you'll see the error:

```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@nuxt/bridge/node_modules/defu/dist/defu.cjs?import' does not provide an export named 'defu' (at composables.mjs:3:10)
```

I think as a side effect, hot-reloading doesn't work... At least it's not working for me in an existing app that was migrated.

---------------

## Reproduction Repo:
https://github.com/JamieCurnow/nuxt-bridge-defu-bug

### Describe the bug

After running `npm run dev` I open the app in the browser and get the following error message:

```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@nuxt/bridge/node_modules/defu/dist/defu.cjs?import' does not provide an export named 'defu' (at composables.mjs:3:10)
```

Potentially this kills HMR, though I haven't tested this extensively enough to know if it's related.

**Comment by Luferov** [comment]
Same.
