### ISSUE TITLE
Problems with imports: ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by P4sca1** [nuxt/bridge#344]
### Environment

Nuxt CLI v3.0.0-rc.3-27536597.3359b3b
RootDir: /sandbox
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27530716.c4f8671`
------------------------------

### Reproduction

https://codesandbox.io/s/async-platform-s1qn8l

### Describe the bug

The app works fine in development, but is not working after building.
`yarn build`, followed by `yarn start` does not work.

### Additional context

I noticed that the `ufo` package is missing a `package.json`, which might be the reason for the issue.
In my private app, I replaced all import of `ufo` with `ufo/dist/index.mjs`, which fixed the error for `ufo` , but reveiled additional im port related errors. 

### Logs

```shell
sandbox@sse-sandbox-s1qn8l:/sandbox$ node .output/server/index.mjs
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/sandbox/.output/server/node_modules/ufo/' imported from /sandbox/.output/server/index.mjs
Did you mean to import ufo/dist/index.cjs?
    at new NodeError (internal/errors.js:322:7)
    at legacyMainResolve (internal/modules/esm/resolve.js:245:9)
    at packageResolve (internal/modules/esm/resolve.js:680:14)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

```
[nuxt] [request error] Cannot find package '/Users/pascal/code/ips-hosting/frontend/.output/server/node_modules/graphql/' imported from /Users/pascal/code/ips-hosting/frontend/.output/server/chunks/app/server.mjs
  at new NodeError (node:internal/errors:371:5)
  at legacyMainResolve (node:internal/modules/esm/resolve:335:9)
  at packageResolve (node:internal/modules/esm/resolve:877:14)
  at moduleResolve (node:internal/modules/esm/resolve:929:18)
  at defaultResolve (node:internal/modules/esm/resolve:1044:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
```
```

**Comment by Tcharlyson** [comment]
I reproduce exactly the same, my workaround is to fix the ufo version of all dependencies directly at the end of my `package.json`:

With yarn 

```
...
"resolutions": {
   "ufo": "^0.8.4"
}
```

**Comment by engelrolling** [comment]
The npm equivalent doesn't seem to work though, I replaced `resolutions` with `overrides`

**Comment by danielroe** [comment]
Is this still an issue for you? I cannot reproduce it.

**Comment by dargmuesli** [comment]
It indeed looks very much fixed to me! <3

**Comment by P4sca1** [comment]
After refreshing my lock file to upgrade all dependencies, I can confirm that the issue is gone.
