### ISSUE TITLE
 FATAL  [nitro] Please use nuxt generate for static target 

### ISSUE THREAD

**Issue by MartinX3** [nuxt/bridge#386]
### Environment

Nuxt CLI v3.0.0-rc.4                                                                                                                           01:49:56
RootDir: /home/developer/verein/rtc-koeln/Rad-Touristik-Club-Koln-e-V-1972.github.io                                                           01:49:56
Nuxt project info:                                                                                                                             01:49:56

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.4.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `npm@8.13.0`
- Builder:          `webpack`
- User Config:      `build`, `buildModules`, `components`, `css`, `head`, `modules`, `plugins`, `ssr`, `target`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/stylelint-module@4.1.0`, `@nuxtjs/vuetify@1.12.3`, `@pinia/nuxt@0.1.9`, `@nuxt/bridge@3.0.0-27616818.bab9f4b`
------------------------------

### Reproduction

Using SSR and static target `nuxi generate` is broken.

### Describe the bug

Using SSR and static target `nuxi generate` is broken.

### Additional context

```
ssr: false,
target: 'static',
```

### Logs

```shell
/usr/bin/npm run build

> rad-touristik-club-koln-e-v-1972.github.io@1.0.0 build
> nuxi generate

Nuxt CLI v3.0.0-rc.4                                                                                                                        01:48:54

 FATAL  [nitro] Please use nuxt generate for static target                                                                                  01:48:56

  at setupNitroBridge (node_modules/@nuxt/bridge/dist/chunks/module.mjs:149:11)
  at node_modules/@nuxt/bridge/dist/chunks/module.mjs:1237:15
  at node_modules/hable/dist/hable.js:1:990
  at node_modules/hable/dist/hable.js:1:208
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:49:5)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)

ℹ Production build                                                                                                                          01:48:56
ℹ Bundling only for client side                                                                                                             01:48:56
ℹ Target: static                                                                                                                            01:48:56
ℹ Using components loader to optimize imports                                                                                               01:48:56
ℹ Discovered Components: .nuxt/components/readme.md                                                                                         01:48:56
✔ Builder initialized                                                                                                                       01:48:56
✔ Nuxt files generated                                                                                                                      01:48:56

✖ Client
  Compiled with some errors in 59.81s


Hash: bbc446c7cde2fef28db6
Version: webpack 4.46.0
Time: 59812ms
Built at: 07.07.2022 01:49:57
                           Asset       Size            Chunks               Chunk Names
                      03603e4.js   7.26 KiB             14, 6  [immutable]  pages/contact
                      0bf30cc.js   2.14 KiB                16  [immutable]  pages/index
                      0dff4da.js    242 KiB                 5  [immutable]  commons/app
                      188ff9c.js   49.8 KiB                 1  [immutable]  vendors/components/page-calendar-c-list/components/page-calendar-list-filter-c-categories/pages/calendar
                      1bd4a24.js   6.17 KiB         9, 11, 12  [immutable]  components/page-calendar-c-list
                      28246e3.js   1.61 MiB                18  [immutable]  vendors/app
                      2dae8c5.js  679 bytes                10  [immutable]  components/page-calendar-list-c-search
                      2f7c4be.js   68.8 KiB  13, 8, 9, 11, 12  [immutable]  pages/calendar
                      33d119d.js   55.6 KiB                 2  [immutable]  vendors/components/page-calendar-c-list/components/page-calendar-list-filter-c-date-range/pages/calendar
                      400d256.js   2.46 KiB                17  [immutable]  runtime
                      42ffb94.js   5.19 KiB                 7  [immutable]  components/page-c-guestbook
                      4f50631.js   4.52 KiB                 6  [immutable]  components/page-c-contact
                      59202ba.js     74 KiB                 4  [immutable]  app
                      5d6f247.js   48.9 KiB                 0  [immutable]  vendors/components/page-calendar-c-list/components/page-calendar-list-c-search/components/page-calen/268ca519
                      7d018b1.js   63.6 KiB                 3  [immutable]  vendors/components/page-calendar-c-list/pages/calendar
                      93cb8b6.js   1.42 KiB                12  [immutable]  components/page-calendar-list-filter-c-date-range
                      94b3ae4.js  672 bytes                11  [immutable]  components/page-calendar-list-filter-c-categories
                        LICENSES   3.73 KiB                                 
                      aaf2c86.js   75.9 KiB             15, 7  [immutable]  pages/guestbook
                      d458dfd.js   2.32 KiB                 8  [immutable]  components/page-calendar-c-control
fonts/TacticSans-Bld.d0dcd35.otf   66.3 KiB                    [immutable]  
fonts/TacticSans-Reg.745135e.otf   64.5 KiB                    [immutable]  
 img/banner_vertikal.cc7568d.svg   3.99 KiB                    [immutable]  
Entrypoint app = 400d256.js 0dff4da.js 28246e3.js 59202ba.js

ERROR in ./.nuxt/dist.plugin.912f87cc.mjs
Module not found: Error: Can't resolve 'vue-demi' in '/home/developer/verein/rtc-koeln/Rad-Touristik-Club-Koln-e-V-1972.github.io/.nuxt'
 @ ./.nuxt/dist.plugin.912f87cc.mjs 1:0-49 4:4-10 5:2-9 6:25-29 6:32-36 6:47-51 13:6-12
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

ERROR in ./node_modules/@nuxt/bridge/dist/runtime/app.plugin.mjs 102:59
Module parse failed: Unexpected token (102:59)
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
|     get (target, prop) {
|       if (prop[0] === '$') {
>         return target.nuxt2Context[prop] || target.vue2App?.[prop]
|       }
|       return Reflect.get(target, prop)
 @ ./.nuxt/index.js 36:0-76 290:25-55 296:19-49
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

ERROR in ./node_modules/@nuxt/bridge/dist/runtime/composables.mjs 27:27
Module parse failed: Unexpected token (27:27)
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
|         return target.public;
|       }
>       return target[prop] ?? target.public[prop];
|     },
|     set(target, prop, value) {
 @ ./node_modules/@nuxt/bridge/dist/runtime/index.mjs 2:0-34 2:0-34
 @ ./.nuxt/capi.plugin.mjs
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

 ERROR  Nuxt build error                                                                                                                    01:49:57

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack-edge/dist/webpack.js:1870:21)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack-edge/dist/webpack.js:1835:5)
  at async Builder.build (node_modules/@nuxt/builder-edge/dist/builder.js:262:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:41:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/generate.mjs:28:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)


Process finished with exit code 1
```
```

**Comment by MartinX3** [comment]
Duplicate of https://github.com/nuxt/bridge/issues/365
