### ISSUE TITLE
config.srcDir invalidate

### ISSUE THREAD

**Issue by poyoho** [nuxt/bridge#422]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.15.8`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```js
export default defineNuxtConfig({
  srcDir: 'src/',
  buildModules: ['@unocss/nuxt', '@nuxt/bridge-edge'],
  components: true,
  bridge: {
    vite: true,
    icons: true
  },
  css: ['@unocss/reset/tailwind.css'],
  vite: {
  },
  unocss: {
    uno: true,
    attributify: true,
    icons: {
      scale: 1.2
    }
  },
  icons: {}
})
```

### Describe the bug

when setting `srcDir` nuxt will throw an error.

```text
[unocss] entry module not found, have you add `import 'uno.css'` in your main entry?
[nuxt] [request error] _createApp is not a function
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/index.mjs:264:25)  
  at async ./.nuxt/dev/index.mjs:496:20  
  at async /node_modules/.pnpm/h3@0.7.10/node_modules/h3/dist/index.mjs:420:19  
  at async Server.nodeHandler (/node_modules/.pnpm/h3@0.7.10/node_modules/h3/dist/index.mjs:370:7)
```

### Additional context

but setting `config.buildDir` inside of the `srcDir` nuxt will run well. 

for example:

```js
export default defineNuxtConfig({
  srcDir: 'src/',
  buildDir: 'src/.nuxt/',
  buildModules: ['@unocss/nuxt', '@nuxt/bridge-edge'],
  components: true,
  bridge: {
    vite: true,
    icons: true
  },
  css: ['@unocss/reset/tailwind.css'],
  vite: {
  },
  unocss: {
    uno: true,
    attributify: true,
    icons: {
      scale: 1.2
    }
  },
  icons: {}
})
```

_No response_

**Comment by Ttou** [comment]
same problem

**Comment by emretepedev** [comment]
Same issue here.

**Comment by wattanx** [comment]
Close as no further investigation is possible as no reproduction is available.
If it is still occurring, please create a reproduction.
