### ISSUE TITLE
Context is not available

### ISSUE THREAD

**Issue by nestle49** [nuxt/bridge#474]
### Environment

Nuxt CLI v3.0.0-rc.7   (bridge)

### Reproduction

nuxt/bridge (Nuxt CLI v3.0.0-rc.7) + last version @nuxt/pinia

with rc-6 have not this error

### Describe the bug

After npm run dev

### Logs

```shell
FATAL  Context is not available                                                                                                                                                                                              12:32:52

  at Object.use (node_modules/unctx/dist/index.mjs:12:15)
  at ModuleContainer.<anonymous> (node_modules/@nuxt/bridge/module.cjs:31:17)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:174:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)

 ERROR  Cannot start nuxt:  Context is not available                                                                                                                                                                          12:41:57

  at Object.use (node_modules/unctx/dist/index.mjs:12:15)
  at ModuleContainer.<anonymous> (node_modules/@nuxt/bridge/module.cjs:31:17)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:174:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)

```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by nestle49** [comment]
Sorry, I cant't create full project, because his under NDA, also it take a lot of time

I can show config and package if needed. I completed all steps by guide migration to bridge and run 'npm run dev'

Also, same problem:
https://github.com/nuxt/bridge/issues/473
https://github.com/nuxt/framework/discussions/6557

**Comment by joshmossas** [comment]
This bug is gone in the latest RC. See #473
