### ISSUE TITLE
nuxtApp availability in nuxt 2 middleware

### ISSUE THREAD

**Issue by psycongaroo** [nuxt/bridge#48]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `target`, `head`, `publicRuntimeConfig`, `privateRuntimeConfig`, `loading`, `css`, `buildModules`, `build`, `router`, `components`, `vite`, `bridge`, `plugins`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/core/nuxt@6.9.2`, `@nuxt/bridge-edge@3.0.0-27369360.33ebb01`, `@pinia/nuxt@0.1.8`

### Reproduction

- use nuxt bridge
- create a route middleware
- use in it the composables, useCookie

### Describe the bug

useCookie not working in middleware:

```
`nuxt app instance unavailable

at Module.useNuxtApp (file://./.nuxt/dist/server/server.mjs:11336:13)
at useSSRReq (file://./.nuxt/dist/server/server.mjs:11682:52)
at readRawCookies (file://./.nuxt/dist/server/server.mjs:11690:40)
at Module.useCookie (file://./.nuxt/dist/server/server.mjs:11664:19)
at file://./.nuxt/dist/server/server.mjs:11266:47
at promisify (file://./.nuxt/dist/server/server.mjs:12117:15)
at Module.middlewareSeries (file://./.nuxt/dist/server/server.mjs:12093:10)
at __vite_ssr_exports__.default (file://./.nuxt/dist/server/server.mjs:175:31)
at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)
at async renderMiddleware (file://./.nuxt/nitro/index.mjs:191:20)`
```

**Comment by Tcharlyson** [comment]
> @Atinux @danielroe @pi0 same identical problem using $fetch inside middleware
> 
> I know is same reason about useCookie, but I wanted to report it too.

Same issue here, using $fetch inside a middleware

**Comment by wattanx** [comment]
Closing this due to inactivity. If the issue persists, please open a new issue.
