### ISSUE TITLE
nuxt app instance unavailable with Apollo Graphql

### ISSUE THREAD

**Issue by Luferov** [nuxt/bridge#485]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `ssr`, `app`, `alias`, `target`, `publicRuntimeConfig`, `head`, `modules`, `apollo`, `typescript`, `css`, `plugins`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`, `bridge`, `buildModules`
- Runtime Modules:  `@nuxtjs/color-mode@3.1.4`, `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/i18n@7.2.3`, `@nuxtjs/vuetify@1.12.3`, `@pinia/nuxt@0.4.0`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27672061.a645f7f`
------------------------------

### Reproduction

https://github.com/Luferov/nuxt-graphql-bug

git clone git@github.com:Luferov/nuxt-graphql-bug.git
cd nuxt-graphql-bug
yarn

OK, its work! But

rm -r node_modules && rm -r .nuxt && yarn

It is not work.

### Describe the bug

I created `yarn.lock` from my project and project is wok. But if delete `yarn.lock` and run command `yarn`, Nuxt will update up nuxt 3-rc and project is not working.

![image](https://user-images.githubusercontent.com/26242554/184549729-66b95a29-aab9-4495-b3ec-841b4e121f35.png)

![image](https://user-images.githubusercontent.com/26242554/184549745-2571a66c-9c39-4a05-a8f6-831bc5437b08.png)

### Logs

```shell
[nuxt] [request error] nuxt app instance unavailable
  at useNuxtApp (./.nuxt/dist/server/server.js:15661:13)  
  at useRuntimeConfig (./.nuxt/dist/server/server.js:16127:78)  
  at ./.nuxt/dist/server/server.js:66176:68  
  at module.exports../.nuxt/apollo-module.js.__webpack_exports__.default (./.nuxt/dist/server/server.js:404:25)  
  at createApp (./.nuxt/dist/server/server.js:1463:93)  
  at async module.exports../.nuxt/server.js.__webpack_exports__.default (./.nuxt/dist/server/server.js:3687:7)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/index.mjs:264:19)  
  at async ./.nuxt/dev/index.mjs:499:20  
  at async ./node_modules/h3/dist/index.mjs:492:19  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:438:7)
```

**Comment by Luferov** [comment]
May it depend with https://github.com/nuxt/bridge/issues/436

**Comment by Luferov** [comment]
@danielroe ping :)
