### ISSUE TITLE
Nuxt bridge stops on loading with many errors

### ISSUE THREAD

**Issue by nestle49** [nuxt/bridge#502]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `npm@8.5.5`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

no repro, just migrate nuxt bridge

### Describe the bug

```
Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):                                                                                                                                  friendly-errors 13:25:38
[@vue/compiler-sfc] `defineProps()` in <script setup> cannot reference locally declared variables because it will be hoisted outside of the setup() function. If your component options require initialization in the module scope, use a separate normal <script> to export the options instead.
```

```
'@nuxt/devalue' is imported by node_modules/@nuxt/bridge/dist/runtime/nitro/renderer.mjs, but could not be resolved – treating it as an external dependency

Module build failed (from ./node_modules/vue-loader/lib/index.js):                                                                                                                                            friendly-errors 13:25:38
TypeError: Cannot read properties of null (reading 'content')
    at selectBlock (/Users/developer/PhpstormProjects/core/node_modules/vue-loader/lib/select.js:30:41)
    at Object.module.exports (/Users/developer/PhpstormProjects/core/node_modules/vue-loader/lib/index.js:89:12)

```

with 
```
bridge: {
 vite: true
}
```

```
✘ [ERROR] Could not resolve "#app"

    node_modules/@nuxt/bridge/dist/runtime/ssr.mjs:1:27:
      1 │ import { useNuxtApp } from "#app";
        ╵                            ~~~~~~

  You can mark the path "#app" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "#app"

    node_modules/@nuxt/bridge/dist/runtime/asyncData.mjs:2:27:
      2 │ import { useNuxtApp } from "#app";
        ╵                            ~~~~~~

  You can mark the path "#app" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "#app"

    node_modules/@nuxt/bridge/dist/runtime/cookie.mjs:6:27:
      6 │ import { useNuxtApp } from "#app";
        ╵                            ~~~~~~

  You can mark the path "#app" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not read from file: /Users/developer/PhpstormProjects/core/node_modules/@nuxt/bridge/dist/runtime/vite/mock/whatwg-url.mjs/webidl2js-wrapper

    node_modules/jsdom/lib/jsdom/living/interfaces.js:14:15:
      14 │   URL: require("whatwg-url/webidl2js-wrapper").URL,
         ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


```

### Logs

```shell
'@nuxt/devalue' is imported by node_modules/@nuxt/bridge/dist/runtime/nitro/renderer.mjs, but could not be resolved – treating it as an external dependency
```

**Comment by AndrewBogdanovTSS** [comment]
> no repro, just migrate nuxt bridge
@nestle49 if you treat the community in such a way - your issues will never get resolved. Creating a repro usually takes a couple of minutes, it's just 3 easy steps:
1. Fork https://github.com/antfu/vitesse-nuxt-bridge
2. Open https://stackblitz.com/
3. Connect your GitHub, select repo, and share a link here
