### ISSUE TITLE
The "path" argument must be of type string. Received an instance of Array/undefined

### ISSUE THREAD

**Issue by AndreyYolkin** [nuxt/bridge#515]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `2.16.0-27704181.7b3bab3`
- Nitro Version:    `0.4.24`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `bridge`, `serverHandlers`, `devServerHandlers`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27700335.6dfc006`
------------------------------

### Reproduction

https://github.com/AndreyYolkin/nuxt-bug-path-argument

### Describe the bug

When we are starting app in dev mode, something goes wrong and nuxt reporting that some package paths are broken. Some paths consist of Array, some are undefined.

### Additional context

Package name in logs (`@nuxt/ui-templates`) appeared because I tried to wrap module resolving function in try catch to determine the broken package. Howerer, it actually didn't help a lot

### Logs

```shell
ERROR  @nuxt/ui-templates The "path" argument must be of type string. Received an instance of Array                                                                                                19:24:41

  at new NodeError (node:internal/errors:387:5)
  at validateString (node:internal/validators:121:11)
  at Object.resolve (node:path:1098:7)
  at Function.Module._nodeModulePaths (node:internal/modules/cjs/loader:642:17)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:896:37)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at resolveModule (node_modules/nuxi/dist/shared/nuxi.a3ba4610.mjs:17:31)
  at importModule (node_modules/nuxi/dist/shared/nuxi.a3ba4610.mjs:40:24)
  at loadingHandler (node_modules/nuxi/dist/chunks/dev.mjs:6727:50)
  at Server.serverHandler (node_modules/nuxi/dist/chunks/dev.mjs:6733:58)


 ERROR  [unhandledRejection] The "path" argument must be of type string. Received undefined                                                                                                         19:24:41

  at new NodeError (node:internal/errors:387:5)
  at validateString (node:internal/validators:121:11)
  at Object.resolve (node:path:1098:7)
  at pathToFileURL (node:internal/url:1496:25)
  at importModule (node_modules/nuxi/dist/shared/nuxi.a3ba4610.mjs:41:17)
  at loadingHandler (node_modules/nuxi/dist/chunks/dev.mjs:6727:50)
  at Server.serverHandler (node_modules/nuxi/dist/chunks/dev.mjs:6733:58)
  at Server.emit (node:events:525:35)
  at Server.emit (node:domain:489:12)
  at parserOnIncoming (node:_http_server:980:12)
```

**Comment by danielroe** [comment]
I can't reproduce with your reproduction.

**Comment by AndrewBogdanovTSS** [comment]
I confirm that the issues appeared after upgrading to latest bridge version

**Comment by nestle49** [comment]
Same error

**Comment by wtagain** [comment]
Same error.
But the problem has gone away after I update npm@latest.
Also delete all node_modules & package-lock.json, and npm i.

**Comment by vladislav-sevostyanov** [comment]
I have the same

**Comment by alih70442** [comment]
The same one

**Comment by wilOliw** [comment]
+1

**Comment by thisismydesign** [comment]
How do I revert to a working version?

**Comment by Envoy49** [comment]
got the same error after upgrading `"nuxt-edge": "^2.16.0-27358576.777a4b7f"` to this `"nuxt-edge": "^2.16.0-27708500.54e852f"`

**Comment by AndrewBogdanovTSS** [comment]
OMG, I was simply missing index.vue in pages folder, what a facepalm moment 🤦‍♂️🤦‍♂️🤦‍♂️
