### ISSUE TITLE
vue-query loses context during server-side rendering 

### ISSUE THREAD

**Issue by AndreyYolkin** [nuxt/bridge#542]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27718583.54e852f`
- Package Manager:  `npm@8.16.0`
- Builder:          `vite`
- User Config:      `head`, `plugins`, `bridge`, `serverHandlers`, `devServerHandlers`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27719140.5e5fa50`

### Reproduction

https://github.com/AndreyYolkin/nuxt-bridge-vue-query

https://stackblitz.com/github/AndreyYolkin/nuxt-bridge-vue-query?file=pages%2FvueQuery.vue (plugin is loading into application only after editing nuxt.config)

### Describe the bug

Usage of vue-query is a bit strange. When we navigate to the page with vue-query useQuery composable inside `setup()` function, everything is ok on client-side. However, if we refresh the page, useQuery fails on server-side with error `vue-query hooks can only be used inside setup() function`. 

### Additional context

Copied from https://github.com/DamianOsipiuk/vue-query/issues/244

### Logs

```shell
[nuxt] [request error] vue-query hooks can only be used inside setup() function.
  at useQueryClient (/C:/Projects/nuxt-bridge-fonts/node_modules/vue-query/lib/index.mjs:58:15)
  at useBaseQuery (/C:/Projects/nuxt-bridge-fonts/node_modules/vue-query/lib/index.mjs:533:25)
  at Module.useQuery (/C:/Projects/nuxt-bridge-fonts/node_modules/vue-query/lib/index.mjs:588:20)
  at setup (/C:/Projects/nuxt-bridge-fonts/.nuxt/dist/server/server.mjs:15683:54)
  at invokeWithErrorHandling (/C:/Projects/nuxt-bridge-fonts/.nuxt/dist/server/server.mjs:3326:30)
  at initSetup (/C:/Projects/nuxt-bridge-fonts/.nuxt/dist/server/server.mjs:2749:27)
  at initState (/C:/Projects/nuxt-bridge-fonts/.nuxt/dist/server/server.mjs:5659:5)
  at VueComponent.Vue._init (/C:/Projects/nuxt-bridge-fonts/.nuxt/dist/server/server.mjs:5985:9)
  at new VueComponent (/C:/Projects/nuxt-bridge-fonts/.nuxt/dist/server/server.mjs:6120:18)
  at createComponentInstanceForVnode (C:\Projects\nuxt-bridge-fonts\node_modules\vue-server-renderer\build.dev.js:2534:12)
```

**Comment by danielroe** [comment]
The issue here is that `vue-query` has its own import of `vue` (through `vue-demi`) and this ends up being different from the `vue` used by Nuxt. To resolve, you can transpile both deps:

```js
