### ISSUE TITLE
Error pages are completely broken

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/bridge#636]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `bridge`, `ssr`, `target`, `buildModules`, `telemetry`, `serverHandlers`, `devServerHandlers`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27778503.de9e5c2`

### Reproduction

https://github.com/daniluk4000/nuxt-bridge-nonworking-error-page

### Describe the bug

When you have an error and error.vue in template (or even you don't have error.vue) everything breaks for Nuxt Bridge with `Error while generating error response FetchError`

### Logs

```shell
[nitro] Error while generating error response FetchError: 500  (/__nuxt_error?url=/&statusCode=500&statusMessage&message=oops&description=%3Cpre%3E%3Cspan+class=%22stack%22%3Eat+setup+(./.nuxt/dist/server/server.js:3444:11)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+invokeWithErrorHandling+(./.nuxt/dist/server/server.js:12318:26)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+initSetup+(./.nuxt/dist/server/server.js:11780:25)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+initState+(./.nuxt/dist/server/server.js:14523:3)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+Vue._init+(./.nuxt/dist/server/server.js:14812:5)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+new+VueComponent+(./.nuxt/dist/server/server.js:14941:12)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+createComponentInstanceForVnode+(./node_modules/vue-server-renderer/build.dev.js:2530:12)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+renderComponentInner+(./node_modules/vue-server-renderer/build.dev.js:7218:45)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+renderComponent+(./node_modules/vue-server-renderer/build.dev.js:7195:9)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+RenderContext.renderNode+(./node_modules/vue-server-renderer/build.dev.js:7112:9)%3C/span%3E%3C/pre%3E&data)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.errorhandler [as onError] (file:///WebstormProjects/bridge-test/.nuxt/dev/index.mjs:424:16)
    at async Server.toNodeHandle (file:///WebstormProjects/bridge-test/node_modules/h3/dist/index.mjs:705:9)
```

**Comment by wattanx** [comment]
Are you still encountering this?
The latest version does not seem to reproduce the same error in the reproduction you provided.

**Comment by daniluk4000** [comment]
We've migrated to Nuxt CAPI instead of Bridge due to many errors. When we have a chance I'll try to migrate again and will say the result.
