### ISSUE TITLE
vite: workaround no longer needed

### ISSUE THREAD

**Issue by AndreyYolkin** [nuxt/bridge#649]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `bridge`, `serverHandlers`, `devServerHandlers`, `typescript`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27830071.32c4527`
------------------------------

### Reproduction

https://stackblitz.com/github/AndreyYolkin/latest-bridge-vite-workaround-issue
https://github.com/AndreyYolkin/latest-bridge-vite-workaround-issue

### Describe the bug

Nuxt bridge with fresh dependencies uses vite which causes 404 errors for assets. Fast search in source code returned workaround for vite, which no longer needed as far as I concerned. Removing this 3 lines helps to run dev server without errors.
![image](https://user-images.githubusercontent.com/11289484/204835121-757ac395-a522-41a5-9eab-5dc9e6991617.png)

### Additional context

https://github.com/nuxt/bridge/blob/0fb6cfcd17971ebefdaed3dece5af57a726921a6/src/vite/client.ts#L113-L115

### Logs

```shell
ERROR  6:08:55 PM [vite] Internal server error: ENOENT: no such file or directory, open '/__url/.nuxt/components/nuxt-error.vue'                                                                                                                                                                                            18:08:55
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at getDescriptor (file:///home/user/family/latest-bridge/node_modules/@vitejs/plugin-vue2/dist/index.mjs:2225:66)
      at Context.load (file:///home/user/family/latest-bridge/node_modules/@vitejs/plugin-vue2/dist/index.mjs:3210:28)
      at Object.load (file:///home/user/family/latest-bridge/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40201:46)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async loadAndTransform (file:///home/user/family/latest-bridge/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36553:24)


 ERROR  6:08:55 PM [vite] Internal server error: ENOENT: no such file or directory, open '/__url/.nuxt/components/nuxt-loading.vue'                                                                                                                                                                                          18:08:55
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at getDescriptor (file:///home/user/family/latest-bridge/node_modules/@vitejs/plugin-vue2/dist/index.mjs:2225:66)
      at Context.load (file:///home/user/family/latest-bridge/node_modules/@vitejs/plugin-vue2/dist/index.mjs:3210:28)
      at Object.load (file:///home/user/family/latest-bridge/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40201:46)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async loadAndTransform (file:///home/user/family/latest-bridge/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36553:24)
```

**Comment by AndreyYolkin** [comment]
Yes, I found this lines in your PR. Great job!
