### ISSUE TITLE
useFetch in capi.legacy does not work with nuxt start.

### ISSUE THREAD

**Issue by wattanx** [nuxt/bridge#730]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.17.0-28005141.1ab8718`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `webpack`
- User Config:      `ssr`, `bridge`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@0.10.1`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-3fgb91

### Describe the bug

`useFetch` in `capi.legacy` does not work with nuxt start.
The following console error is displayed.

There is no problem in the case of `nuxt dev`.

### Additional context

Since nitro is not used, the `nuxt` command is used.

capi.legacy's `useFetch` executes `loadFullStatic`.

but `useFetch` in `@nuxtjs/composition-api` does not execute `loadFullStatic`.

I think there might be a difference in the following conditions.
https://github.com/nuxt/bridge/blob/main/packages/bridge/src/runtime/capi.legacy.ts#L529
https://github.com/nuxt-community/composition-api/blob/main/src/runtime/composables/fetch.ts#L345

### Logs

```shell
9811020.js:1 TypeError: Cannot read properties of undefined (reading '')
    at de90620.js:1:3573
    at k (de90620.js:1:3795)
    at de90620.js:1:7188
    at E (de90620.js:1:7492)
    at setup (cd11293.js:1:222)
    at ln (9811020.js:1:21634)
    at 9811020.js:1:36652
    at Pr (9811020.js:1:36863)
    at t._init (9811020.js:1:41237)
    at new f (9811020.js:1:38735)
```

**Comment by wattanx** [comment]
The issue has been resolved in the latest version!

@danielroe 
Thank you for your support. It was very helpful.
