### ISSUE TITLE
Disabling nitro breaks nuxi dev

### ISSUE THREAD

**Issue by gluebi** [nuxt/bridge#808]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     2.17.1-28110261.f875ec7
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          webpack
- User Config:      head, css, plugins, components, buildModules, modules, build, bridge, ssr, serverHandlers, devServerHandlers, devServer, typescript, nitro
- Runtime Modules:  -
- Build Modules:    (), @nuxt/bridge@3.0.0-28109745.a6e6787
------------------------------

### Reproduction

https://stackblitz.com/edit/github-flq73p

### Describe the bug

Running `nuxi dev` with nitro: false option results in the following error: ` ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'onError')`

### Additional context

nuxt.config.js
```
import { defineNuxtConfig } from '@nuxt/bridge';

export default defineNuxtConfig({
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'Nuxt Starter',
    htmlAttrs: {
      lang: 'en',
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    transpile: ['ofetch'],
  },
  bridge: {
    nitro: false,
  },
  ssr: false,
});

```

### Logs

```shell
ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'onError')                  12:01:03

  at toNodeHandle (file://node_modules/nuxi/dist/chunks/index2.mjs:531:23)
  at Server.serverHandler (file://node_modules/nuxi/dist/chunks/dev.mjs:133:31)
  at EventEmitter.emit (https://githubflq73p-avrk.w-credentialless.staticblitz.com/blitz.4952a0f3.js:35:156948)
  at S.emit (https://githubflq73p-avrk.w-credentialless.staticblitz.com/blitz.4952a0f3.js:35:1539522)
  at parserOnIncoming (https://githubflq73p-avrk.w-credentialless.staticblitz.com/blitz.4952a0f3.js:35:903037)
  at _0x1725a9.parserOnHeadersComplete (https://githubflq73p-avrk.w-credentialless.staticblitz.com/blitz.4952a0f3.js:35:431493)
  at https://githubflq73p-avrk.w-credentialless.staticblitz.com/blitz.4952a0f3.js:44:390689
  at _0x4597db (https://githubflq73p-avrk.w-credentialless.staticblitz.com/blitz.4952a0f3.js:44:153274)
  at https://githubflq73p-avrk.w-credentialless.staticblitz.com/blitz.4952a0f3.js:44:153023
  ```
```

**Comment by wattanx** [comment]
We have noted this in the documentation and will close it.
Thank you for creating the issue!
https://github.com/nuxt/nuxt/pull/21586
