### ISSUE TITLE
Dev server doesn't work with nitro: false option

### ISSUE THREAD

**Issue by deleteme** [nuxt/bridge#834]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `2.17.0`
- Nitro Version:    `2.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `build`, `bridge`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `nitro`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-28125529.9b0a98e`

### Reproduction

https://github.com/deleteme/nuxt2-bridge-nitro-bug

### Describe the bug

The `nuxi dev` command starts a local development server.

Nuxt Bridge has a `nitro` option, described as "Use legacy server instead of Nitro". When Nitro is disabled with `nitro: false`, this dev server is broken.

#### Demo of the bug

Also notice that initially during building, "Nuxt 2.17.0 with Nitro 2.5.1" momentarily appears at the top of the output. The "with Nitro" part is unexpected and suggests that the `nitro: false` config option isn't working correctly.

https://github.com/nuxt/bridge/assets/9389/8cd9c10f-c95f-474a-a951-1cac31085869

### Additional context

This [reproduction git repository](https://github.com/deleteme/nuxt2-bridge-nitro-bug) contains a fresh Nuxt 2 project via (`yarn create nuxt-app`), with Nuxt Bridge being the only additional package.

This bug was encountered while evaluating Nuxt Bridge. I wanted to know if Nuxt Bridge works (or what parts of it work) in a brand new Nuxt 2 app to determine if it's suitable for use in the migration of a large Nuxt 2 app to Nuxt 3.

### Logs

```shell
After running `yarn dev`:


✔ Client
  Compiled successfully in 1.84s

✔ Server
  Compiled successfully in 1.61s
ℹ Waiting for file changes
```

When making a request to localhost:3000:

```
 ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'onError')

  at toNodeHandle (node_modules/nuxi/dist/chunks/index2.mjs:498:23)
  at Server.serverHandler (node_modules/nuxi/dist/chunks/dev.mjs:118:31)
  at Server.emit (node:events:525:35)
  at Server.emit (node:domain:489:12)
  at parserOnIncoming (node:_http_server:1072:12)
  at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```
```

**Comment by deleteme** [comment]
This isn't a bug, it was a misunderstanding of how to use the option.

In addition to changing the Nuxt config to have `nitro: false`, the original `nuxt` script tasks in package.json need to be restored so that `nuxi` is no longer called.

https://github.com/nuxt/bridge/pull/835
