### ISSUE TITLE
publicPath does not work when using vite

### ISSUE THREAD

**Issue by dmytro-grablov** [nuxt/bridge#872]
### Environment

- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     2.17.0
- Nitro Version:    2.5.2
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      bridge, server, vite, build, serverHandlers, devServerHandlers, devServer, typescript, nitro, buildModules
- Runtime Modules:  -
- Build Modules:    (), @nuxt/bridge@3.0.0-28142286.528efb7

### Reproduction

Please clone this repo and follow readme

https://github.com/dmytro-grablov/nuxt-bridge-assets

### Describe the bug

it is not possible to define a `publicPath` build property when vite is enabled in the bridge configuration

`npx nuxi build` then fails with `Invalid pattern "/[name]-[hash].[ext]" for "output.assetFileNames", patterns can be neither absolute nor relative paths. If you want your files to be stored in a subdirectory, write its name without a leading slash like this: subdirectory/pattern.`

I also tried to directly specify `base` property for vite, to no avail.

### Logs

```shell
dgrablov@XIN720081 nuxt-bridge-assets % npm run build

> nuxt-bug@1.0.0 build
> nuxi build

Nuxi 3.6.1                                                                                                                                            11:30:18 AM
Nuxt 2.17.0 with Nitro 2.5.2                                                                                                                          11:30:18 AM
🧪  Vite mode is experimental and some nuxt modules might be incompatible                                                                             11:30:20 AM
    If you find a bug, please report via https://github.com/nuxt/bridge/issues with a minimal reproduction.
ℹ Production build                                                                                                                                   11:30:20 AM
ℹ Bundling for server and client side                                                                                                                11:30:20 AM
ℹ Target: server                                                                                                                                     11:30:20 AM
✔ Builder initialized                                                                                                                                11:30:20 AM
✔ Nuxt files generated                                                                                                                               11:30:20 AM

[11:30:21 AM]  ERROR  Invalid pattern "/[name]-[hash].[ext]" for "output.assetFileNames", patterns can be neither absolute nor relative paths. If you want your files to be stored in a subdirectory, write its name without a leading slash like this: subdirectory/pattern.


[11:30:21 AM]  ERROR  Invalid pattern "/[name]-[hash].[ext]" for "output.assetFileNames", patterns can be neither absolute nor relative paths. If you want your files to be stored in a subdirectory, write its name without a leading slash like this: subdirectory/pattern.

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
  at renderNamePattern (node_modules/rollup/dist/es/shared/node-entry.js:15499:16)
  at generateAssetFileName (node_modules/rollup/dist/es/shared/node-entry.js:24765:23)
  at FileEmitter.finalizeAssetsWithSameSource (node_modules/rollup/dist/es/shared/node-entry.js:25062:35)
  at FileEmitter.setOutputBundle (node_modules/rollup/dist/es/shared/node-entry.js:24905:22)
  at Bundle.generate (node_modules/rollup/dist/es/shared/node-entry.js:17700:27)
  at node_modules/rollup/dist/es/shared/node-entry.js:26565:40
  at catchUnfinishedHookActions (node_modules/rollup/dist/es/shared/node-entry.js:25698:36)
  at handleGenerateWrite (node_modules/rollup/dist/es/shared/node-entry.js:26563:12)
  at async Object.build (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46477:22)
```

**Comment by wattanx** [comment]
How about setting it to `app.cdnURL`?
https://nuxt.com/docs/api/configuration/nuxt-config#cdnurl

It seems to work with `app.cdnURL`.
(type error, though)
https://stackblitz.com/edit/github-3fgb91-ngp3r7

**Comment by dmytro-grablov** [comment]
Thanks for the hint. However, I have to test it deeper. It seems to work on the test repo, but not on the production project.
I will update with the results

**Comment by dmytro-grablov** [comment]
@wattanx hi, the prop works as expected, thanks a lot for the hint. I was thinking, maybe it makes sense to add it somewhere to the migration guide? This part was not that straightforward/

**Comment by wattanx** [comment]
Glad it worked out!
You are right, it should be in the documentation.

**Comment by wattanx** [comment]
It is already in the latest documentation.
https://nuxt.com/docs/bridge/configuration#buildpublicpath
