### ISSUE TITLE
Error: Nuxt not recognizing SCSS files

### ISSUE THREAD

**Issue by franz-bendezu** [nuxt/bridge#955]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     2.17.2
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          webpack
- User Config:      css, serverHandlers, devServerHandlers, devServer, typescript, nitro, bridge, buildModules
- Runtime Modules:  -
- Build Modules:    (), @nuxt/bridge@3.0.0-rc.2-28307913.ff6077a

### Reproduction

- Clone the project from https://stackblitz.com/edit/github-dwx287-i9namh?file=nuxt.config.ts
- Install dependencies with npm install
- Run npm run dev

### Describe the bug

Nuxt is not recognizing SCSS files during compilation. The error message indicates that relative SCSS modules cannot be found, affecting both the client and server compilation.

### Additional context

- I have verified that the file paths for SCSS files are correct.
- Checked the case sensitivity of the file paths
- All dependencies are up to date (npm install has been run).
- Restarting the Nuxt development server did not resolve the issue.

### Logs

```shell
ERROR  Failed to compile with 1 errors
This relative module was not found:
* ../assets/scss/main.scss in ./.nuxt/App.js
[nuxt] [request error] [unhandled] [500] Cannot find module '../assets/scss/main.scss'
  at webpackMissingModule (./.nuxt/dist/server/server.js:151:45)  
  at ./.nuxt/App.js (./.nuxt/dist/server/server.js:151:144)  
  at __webpack_require__ (./.nuxt/dist/server/server.js:27:30)  
  at ./.nuxt/index.js (./.nuxt/dist/server/server.js:770:84)  
  at __webpack_require__ (./.nuxt/dist/server/server.js:27:30)  
  at ./.nuxt/server.js (./.nuxt/dist/server/server.js:1389:86)  
  at __webpack_require__ (./.nuxt/dist/server/server.js:27:30)  
  at 0 (./.nuxt/dist/server/server.js:23069:18)  
  at __webpack_require__ (./.nuxt/dist/server/server.js:27:30)  
  at module.exports< (./.nuxt/dist/server/server.js:133:18)  
  at  (./.nuxt/dist/server/server.js:136:10)  
  at function (https://githubdwx287i9namh-5owz.w-corp.staticblitz.com/blitz.09144545.js:352:204558)  
  at Module.prototype._compile (node:internal/modules/cjs/loader:55:14883)  
  at Module._extensions[".js"] (node:internal/modules/cjs/loader:55:15564)  
  at Module.prototype.load (node:internal/modules/cjs/loader:55:13469)  
  at Module._load (node:internal/modules/cjs/loader:55:10541)  
  at Module.prototype.require (node:internal/modules/cjs/loader:55:13787)  
  at i (node:internal/modules/cjs/helpers:98:2198)  
  at _0x17a126 (https://githubdwx287i9namh-5owz.w-corp.staticblitz.com/blitz.09144545.js:352:203770)  
  at  (./.nuxt/dist/server/server.cjs:1:93)  
  at function (https://githubdwx287i9namh-5owz.w-corp.staticblitz.com/blitz.09144545.js:352:204558)  
  at Module.prototype._compile (node:internal/modules/cjs/loader:55:14883)  
  at Module._extensions[".js"] (node:internal/modules/cjs/loader:55:15564)  
  at Module.prototype.load (node:internal/modules/cjs/loader:55:13469)  
  at Module._load (node:internal/modules/cjs/loader:55:10541)  
  at  (node:internal/modules/esm/translators:189:2459)  
  at _evaluate (https://githubdwx287i9namh-5owz.w-corp.staticblitz.com/blitz.09144545.js:352:385577)  
  at _evaluate (https://githubdwx287i9namh-5owz.w-corp.staticblitz.com/blitz.09144545.js:352:385692)  
  at evaluate (https://githubdwx287i9namh-5owz.w-corp.staticblitz.com/blitz.09144545.js:352:384768)  
  at run (node:internal/modules/esm/module_job:181:2390)
```

**Comment by wattanx** [comment]
You must also install `sass-loader@^10`.
It works in the following environments
https://stackblitz.com/edit/github-dwx287-rjuos2

**Comment by franz-bendezu** [comment]
@wattanx, thanks a ton for the quick response! 🙌 I gave sass-loader@10 a shot, and it did the trick. Just wanted to mention that it might be helpful to add this workaround to the docs, as it seems to be a common hiccup not explicitly covered there. 
Appreciate your help!

**Comment by wattanx** [comment]
I'm glad it worked out!
This is a nuxt 2 issue and is already documented.
https://v2.nuxt.com/docs/features/configuration/#the-css-property
